name = "wedding-photos-natalia-zhivko"
main = "src/index.js"
compatibility_date = "2025-01-01"

# Bucket must already exist:
# wrangler r2 bucket create wedding-photos-natalia-zhivko
[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "wedding-photos-natalia-zhivko"
